version: '3'

services:

  nexus-0:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /root/nexus-data/0:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - nexus-net

  nexus-1:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8082:8081"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /root/nexus-data/1:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - nexus-net

  haproxy:
    build: haproxy
    ports:
      - "9999:80"
    networks:
      - nexus-net
    volumes_from:
      - syslog-sidecar
    depends_on:
      - nexus-0
      - nexus-1

  syslog-sidecar:
    build: docker-syslog-ng-stdout
    networks:
      - nexus-net

networks:
  nexus-net:
    driver: bridge

volumes:
  syslog-sidecar:

