version: '3'

services:

  nexus-0:
    image: sonatype/nexus3
    ports:
      - "8091:8081"
      - "2424:2424"
      - "2480:2480"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /root/nexus-data/0:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - nexus-net

  nexus-1:
    image: sonatype/nexus3
    ports:
      - "8092:8081"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /root/nexus-data/1:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - nexus-net
  nexus-2:
    image: sonatype/nexus3
    ports:
      - "8093:8081"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /root/nexus-data/2:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - nexus-net
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8081"
    networks:
      - nexus-net
    depends_on:
      - nexus-0
      - nexus-1

networks:
  nexus-net:
    driver: bridge
